# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 574ad806fefe001ed9d43a63061da94c442a596e4f8fd57891169cd5ff051e5b09a58bd2dbf6148c8d681c1a7da6bd12078bde4f8ac9ed1b642ef7e2d11388ab

test:
  secret_key_base: aefab0c2783a46780845f37ebf6a7f5effce085ace4c919ea4305839b1a474dcde7cd41548140caf16a4f732dfb5b4ff30e6a46d9acc327981a4cd3f1ba679d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
